// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b7cce90002934d301bc018cea8aadc3743d87500/react-css-modules/react-css-modules.d.ts
declare module 'react-css-modules' {

    interface TypeOptions {
        allowMultiple?: boolean;
        errorWhenNotFound?: boolean;
    }

    type StylesObject = any;

    interface CSSModules {
        (defaultStyles: StylesObject, options?: TypeOptions): <C extends Function>(Component: C) => C;
        <C extends Function>(Component: C, defaultStyles: StylesObject, options?: TypeOptions): C;
    }

    module CSSModules {
        // Extend your component's Prop interface with this one to get access to `this.props.styles`
        //
        // interface MyComponentProps extends CSSModules.InjectedCSSModuleProps {}
        interface InjectedCSSModuleProps {
            styles?: StylesObject;
        }
    }

    let CSSModules: CSSModules;

    export = CSSModules;
}
